name: 'Kristos*music*universe'
favicon: null
layout_spectrum: 0.42365385964512825
typography_spectrum: 0.4326937885489315
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#040404'
    - '#444444'
    - '#bebebe'
    - '#9f9f9f'
  brandStrength: 0.6875
  lightness: 0.625
  saturation: 0.75
  rhythmicContrast: 0.75
purpose: []
